language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
os:
 - linux
 - osx
matrix:
  allow_failures:
    - os: osx
# command to install dependencies
install:
  - python setup.py -q install
  - pip install unittest2
# command to run tests
script: nosetests